/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_capstone_tayondk_TayoJNI */

#ifndef _Included_com_capstone_tayondk_TayoJNI
#define _Included_com_capstone_tayondk_TayoJNI
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_capstone_tayondk_TayoJNI
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_capstone_tayondk_TayoJNI_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
